name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LISP: sbcl-bin
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libturbojpeg0-dev libffi-dev libheif-dev \
          libtiff-dev build-essential
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          qlot install
          qlot exec ros dynamic-space-size=8gb -l tests/travis.lisp
